//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistorySoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuKien
    {
        public int Id { get; set; }
        public string TenSuKien { get; set; }
        public Nullable<int> NgaySuKien { get; set; }
        public Nullable<int> ThangSuKien { get; set; }
        public Nullable<int> NamSuKien { get; set; }
        public string NoiDungSuKien { get; set; }
    }
}
