//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistorySoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuKien
    {
        public string Id { get; set; }
        public string TenSuKien { get; set; }
        public string NgaySuKien { get; set; }
        public string ThangSuKien { get; set; }
        public string NamSuKien { get; set; }
        public string NoiDungSuKien { get; set; }
    }
}
